### PR TITLE
docs: add initial organization documentation

### PR DESCRIPTION
**Pull request by jpower432**
- Adds a README with org-level organization information (Much of it is from the `compliance-trestle` README)
- Add `CODE_OF_CONDUCT.md` for the org
- Adds LICENSE

[Supported](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) organizational settings for the `.github` repo

### CODE REVIEW

**Review by vikas-agarwal76 — COMMENTED** [review]
@jpower432 I think the Readme file should be at top level and not inside profile directory.

**Comment by jpower432** [comment]
> @jpower432 I think the Readme file should be at top level and not inside profile directory.

@vikas-agarwal76 The README that we want to use as the organization landing page/profile must go in the the profile directory per the GitHub [documentation](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile).

**Comment by jpower432** [comment]
Moving this back into draft while meeting details are being changed

**Comment by jpower432** [comment]
@vikas-agarwal76 Added discussed changes. Note the attached image is a placeholder to we should wait to merge until that is finalized.

**Review by vikas-agarwal76 — APPROVED** [review]
LGTM

**Comment by jpower432** [comment]
@vikas-agarwal76 Made updates based on community repo changes. Once the proper artwork is available in the community repo, I can updated the URL and we can merge.

**Review by vikas-agarwal76 — APPROVED** [review]
LGTM

**Review by vikas-agarwal76 — COMMENTED** [review]
LGTM

**Pull request merged**
